//	Header generated by Constructor for Palm OSª 1.2
//
//	Generated at 17:55:33 Uhr on Dienstag, 17. April 2001
//
//	Generated for file: Harddisk:Play:delphi:astrolib:astrolib:source:astrolib.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OSª;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name: 		"astrolib"
//
//	Palm App Version: 		"1.03"


